services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    networks:
      - rag-network

  rag:
    build: ../rag
    image: ethrozee/rag:latest
    ports:
      - "5000:5000"
    environment:
      - RAGS3_BUCKET=${RAGS3_BUCKET}
    depends_on:
      - ollama
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge